version: '2.4'
services:
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
    environment:  
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
#    image: docker.elastic.co/kibana/kibana:6.7.1
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.vqiu.cn
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  fluentd:
    build: 
      context: ./build
      dockerfile: dockerfile-fluentd
    ports:
      - "24224:24224"
    depends_on:  
      - "elasticsearch"
    volumes:
      - "./config/fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro"
    command: >
      /usr/bin/fluentd -c /fluentd/etc/fluent.conf -v

  backend:
    container_name: backend
    image: hashicorp/http-echo
    restart: always
    ports:
      - "5678:5678"
    command:
      - "-text=Hey, Guys!"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd

volumes:
  esdata:
    driver: local
